export const style = {
  container: {
    marginBottom: 10,
    shadowColor: 'black',
    borderRadius: 5,
    backgroundColor: '#f7f8fa',
    boxShadow: '0px 2px 4px #AEBDCA',
    borderColor: '#ddd',
    borderWidth: 1,
    minHeight: 350,
    marginHorizontal: 10,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    shadowColor: 'black',
    backgroundColor: '#f7f8fa',
    boxShadow: '0px 1px 1px #AEBDCA',
    borderColor: '#ddd',
    borderWidth: 1,
    flex: 1,
    minHeight: 50,
  },
  bodyContainer: {
    shadowColor: 'black',
    backgroundColor: '#fff',
    boxShadow: '0px 1px 1px #fff',
    borderColor: '#ddd',
    borderWidth: 1,
    flex: 6,
    borderTop: '1px solid #ddd',
    borderBottom: '1px solid #ddd',
  },
  topBodyContainer: {
    fontFamily: 'Verdana',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 20px',
    paddingTop: '40px',
  },
  bodySpacer: {
    margin: '0px 0px',
    padding: '10px 20px',
    borderBottom: '1px solid #ddd',
  },
  noSpace: {
    padding: '0px',
    margin: '0px',
  },
  bodyOption: {
    fontFamily: 'Verdana',
    padding: '0px 10px',
    fontAlign: 'center',
    fontSize: '14px',
  },
  footerPlacement: {
    shadowColor: 'black',
    backgroundColor: '#f7f8fa',
    boxShadow: '0px 1px 1px #AEBDCA',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    minHeight: 50,
  },
  buttonPlacement: {
    display: 'flex',
    flexDirecton: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: '12px',
  },
  matButton: {
    backgroundColor: '#d80001',
    padding: '8px 22px',
    borderRadius: 6,
    boxShadow: '0px 2px 4px rgba(0, 0, 0, 0.2)',
    border: 0,
  },
  backImage: {
    margin: '12px',
    width: '25px',
    height: '25px',
  },
};
